# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: Github Blog Broncho
url: http://way1989.github.io
feed: /atom.xml
author_info: <a href="http://wau1989.github.io/">Broncho</a>

myblog:
  gavatar: images/broncho.jpg
  gpname: Broncho
  #linkedin: http://www.linkedin.com/in/taotaoli
  github: https://github.com/way1989
  email: mailto:way.ping.li@gmail.com
  coverimgs: []
  postbgimg: []

categories: [python, books]
